name: visualCaseGen

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - python==3.10
  #- xesmf
  - pip
  - pip:
    #- -e ./external/mom6_bathy/
    #- -e ./external/ipyfilechooser/
    - -e ./ # visualCaseGen
