name: visualCaseGen

channels:
  - conda-forge
  - anaconda
  
dependencies:
  - python>=3.11.10,<3.12
  - libxml2>=2.13,<2.14
  - pip
  - pip:
    - -e ./external/mom6_bathy/
    - -e ./external/ipyfilechooser/
    - -e ./ # visualCaseGen
